const activityConstants = {
  GET_ACTIVITIES_REQUEST: 'GET_ACTIVITIES_REQUEST',
  GET_ACTIVITIES_SUCCESS: 'GET_ACTIVITIES_SUCCESS',
  GET_ACTIVITIES_FAILURE: 'GET_ACTIVITIES_FAILURE',
};

export default activityConstants;
