const itemConstants = {
  ADD_ITEM_REQUEST: 'ADD_ITEM_REQUEST',
  ADD_ITEM_SUCCESS: 'ADD_ITEM_SUCCESS',
  ADD_ITEM_FAILURE: 'UPDATE_USER_FAILURE',

  UPDATE_ITEM_REQUEST: 'UPDATE_USER_REQUEST',
  UPDATE_ITEM_SUCCESS: 'UPDATE_USER_SUCCESS',
  UPDATE_ITEM_FAILURE: 'UPDATE_USER_FAILURE',

  DELETE_ITEM_REQUEST: 'UPDATE_USER_REQUEST',
  DELETE_ITEM_SUCCESS: 'UPDATE_USER_SUCCESS',
  DELETE_ITEM_FAILURE: 'UPDATE_USER_FAILURE',
};

export default itemConstants;
